{
 "title": "Docker",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "container_name",
    "label": "Container name",
    "query": {
     "query": "label_values(docker_container_memory_percentage, container_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU and processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU percentage usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container_name) (docker_container_cpu_percentage{container_name=~\"$container_name\"})",
     "legendFormat": "CPU percentage usage by container $container_name"
    }
   ]
  },
  {
   "title": "CPU percentage usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(container_name) (docker_container_cpu_percentage{container_name=~\"$container_name\"})",
     "legendFormat": "CPU percentage usage by container $container_name"
    }
   ]
  },
  {
   "title": "Number of processes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(container_name) (docker_container_pids{container_name=~\"$container_name\"})",
     "legendFormat": "Number of processes of container $container_name"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory percentage usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container_name) (docker_container_memory_percentage{container_name=~\"$container_name\"})",
     "legendFormat": "Memory usage by container $container_name"
    }
   ]
  },
  {
   "title": "Memory percentage usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(container_name) (docker_container_memory_percentage{container_name=~\"$container_name\"})",
     "legendFormat": "Memory usage by container $container_name"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(container_name) (docker_container_memory_usage_bytes{container_name=~\"$container_name\"})",
     "legendFormat": "Memory usage by container $container_name"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Network throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(container_name) (rate(docker_container_network_tx_bytes{container_name=~\"$container_name\"}[5m]))",
     "legendFormat": "Network bytes received by container $container_name"
    },
    {
     "expr": "avg by(container_name) (-rate(docker_container_network_rx_bytes{container_name=~\"$container_name\"}[5m]))",
     "legendFormat": "Network bytes transmitted by container $container_name"
    }
   ]
  },
  {
   "title": "Block bytes throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(container_name) (rate(docker_container_block_read_bytes{container_name=~\"$container_name\"}[5m]))",
     "legendFormat": "Block bytes read by container $container_name"
    },
    {
     "expr": "avg by(container_name)  (-rate(docker_container_block_write_bytes{container_name=~\"$container_name\"}[5m]))",
     "legendFormat": "Block bytes written by container $container_name"
    }
   ]
  }
 ]
}